// Autogenerated
using System;
using System.Collections.Generic;

namespace NLox.Lib
{
    public abstract class Stmt
    {
        public abstract R Accept<R>(IVisitor<R> visitor);

        public class Expression : Stmt
        {
            public Expr ExpressionValue { get; private init; }
            public override R Accept<R>(IVisitor<R> visitor) => visitor.VisitExpressionStmt(this);
            public Expression(Expr expressionvalue)
            {
                ExpressionValue = expressionvalue;
            }
        }
        public class Print : Stmt
        {
            public Expr ExpressionValue { get; private init; }
            public override R Accept<R>(IVisitor<R> visitor) => visitor.VisitPrintStmt(this);
            public Print(Expr expressionvalue)
            {
                ExpressionValue = expressionvalue;
            }
        }

        public interface IVisitor<R>
        {
            R VisitExpressionStmt(Expression expr);
            R VisitPrintStmt(Print expr);
        }
    }
}