// Autogenerated
using System;
using System.Collections.Generic;

namespace NLox.Lib
{
    public abstract class Stmt
    {
        public abstract R Accept<R>(IStmtVisitor<R> visitor);
    }

    public class ExprStmt : Stmt
    {
        public Expr Expression { get; private init; }
        public override R Accept<R>(IStmtVisitor<R> visitor) => visitor.VisitExprStmtStmt(this);
        public ExprStmt(Expr expression)
        {
            Expression = expression;
        }
    }
    public class PrintStmt : Stmt
    {
        public Expr Expression { get; private init; }
        public override R Accept<R>(IStmtVisitor<R> visitor) => visitor.VisitPrintStmtStmt(this);
        public PrintStmt(Expr expression)
        {
            Expression = expression;
        }
    }

    public interface IStmtVisitor<R>
    {
        R VisitExprStmtStmt(ExprStmt expr);
        R VisitPrintStmtStmt(PrintStmt expr);
    }
}
